// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoIndexing.Domain.Enums;
using VideoIndexing.Infrastructure.EntityFrameworkCore;

namespace VideoIndexing.Infrastructure.Migrations
{
    [DbContext(typeof(VideoIndexingDbContext))]
    partial class VideoIndexingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("VideoIndexing.Domain.Entities.FrameHashBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("ConceptId")
                        .HasColumnType("bigint");

                    b.Property<int>("Discriminator")
                        .HasColumnType("integer");

                    b.Property<long>("FrameId")
                        .HasColumnType("bigint");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FrameHashes","VideoIndexing");

                    b.HasDiscriminator<int>("Discriminator");
                });

            modelBuilder.Entity("VideoIndexing.Domain.Entities.FourFrameHash", b =>
                {
                    b.HasBaseType("VideoIndexing.Domain.Entities.FrameHashBase");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("VideoIndexing.Domain.Entities.OneFrameHash", b =>
                {
                    b.HasBaseType("VideoIndexing.Domain.Entities.FrameHashBase");

                    b.HasDiscriminator().HasValue(0);
                });
#pragma warning restore 612, 618
        }
    }
}
